### ISSUE TITLE
Show [VM] stack frame similar to Chrome

### ISSUE THREAD

**Issue by CrabDude** [trungfinity/traceur-source-maps#2]
Chrome debugger, and consequently node-inspector, shows [VM] stack frames when sourcemaps are available and it is showing sourcemap'd code. This is very nice because it gives you more insight into what the real stack is rather than hiding it / swapping it out.

Thoughts?

**Comment by trungfinity** [comment]
I do not use node-inspector, but there was a pull request to solve this issue #1. What do you think?

**Comment by trungfinity** [comment]
Pushed #1 to npm so inline source map is included.
